# Copyright (c) 2009 XORP, Inc.
#
# This program is free software; you can redistrtrmgrute it and/or modify
# it under the terms of the GNU General Public License, Version 2, June
# 1991 as published by the Free Software Foundation. Redistrtrmgrution
# and/or modification of this program under the terms of any other
# version of the GNU General Public License is not permitted.
#
# This program is distrtrmgruted in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. For more details,
# see the GNU General Public License, Version 2, a copy of which can be
# found in the XORP LICENSE.gpl file.
#
# XORP Inc, 2953 Bunker Hill Lane, Suite 204, Santa Clara, CA 95054, USA;
# http://xorp.net
#
# $Id$

# XXX This is just a placeholder; SCons does not yet support building
# DocBook man pages.
#
#import os
#Import("env")
#
#env = env.Clone()
#
#
#rtrmgr_man = env.DocBookMan(target='xorp_rtrmgr.8', source='xorp_rtrmgr.sgml')
#xorpsh_man = env.DocBookMan(target='xorpsh.8', source='xorpsh.sgml')
#
#Default(rtrmgr_man, xorpsh_man)
