#!/bin/sh

#
# $XORP: xorp/mld6igmp/command_mld6igmp,v 1.3 2003/06/06 23:47:18 pavlin Exp $
#

#
# Send commands to a running MLD6IGMP process.
#

# Conditionally set ${srcdir} if it wasn't assigned (e.g., by `gmake check`)
if [ "X${srcdir}" = "X" ] ; then srcdir=`dirname $0` ; fi

. ${srcdir}/../cli/xrl_cli_shell_funcs.sh
. ${srcdir}/../fea/xrl_mfea_shell_funcs.sh
. ${srcdir}/../mld6igmp/xrl_mld6igmp_shell_funcs.sh

MODULE_NAME="IGMP"
HOSTNAME=`hostname`

echo "Sending command to $MODULE_NAME on $HOSTNAME..."

#
# The first argument should be the command to call.
# The rest of the arguments should be the arguments to the command to call.
#

if [ $# -lt 1 ] ; then
	echo "Usage: $0 <xrl_command> [xrl_command_arguments ... ]"
	exit 1
fi

$*

exit 0
