#!/bin/sh

#
# $XORP: xorp/mld6igmp/configure_mld6igmp,v 1.12 2003/08/14 02:07:10 pavlin Exp $
#

#
# Send configuration commands to a running MLD/IGMP process.
#

MODULE_NAME="PIM-SM"
HOSTNAME=`hostname`

echo "Configuring ${MODULE_NAME} on ${HOSTNAME}..."

# Conditionally set ${srcdir} if it wasn't assigned (e.g., by `gmake check`)
if [ "X${srcdir}" = "X" ] ; then srcdir=`dirname $0` ; fi


###############################################################
# USER CONFIGURATION BEGIN
###############################################################

#
# The IP version. It must be either IPV4 or IPV6
#
IP_VERSION=IPV4
#IP_VERSION=IPV6

. ${srcdir}/../cli/xrl_cli_shell_funcs.sh
. ${srcdir}/../fea/xrl_mfea_shell_funcs.sh
. ${srcdir}/../mld6igmp/xrl_mld6igmp_shell_funcs.sh

#
# Select the vifs to enable
#
case ${HOSTNAME} in
	xorp1)
	ENABLE_VIFS="dc1 dc4"
	;;

	xorp2)
	ENABLE_VIFS="dc1 dc2"
	;;

	xorp3)
	ENABLE_VIFS="dc0 dc1 dc2"
	;;

	xorp4)
	ENABLE_VIFS="eth6 eth7"
	;;

	xorp6)
	ENABLE_VIFS="dc1"
	;;

	possum.icir.org)
	ENABLE_VIFS="rl0"
	;;

	oreo.icir.org)
	ENABLE_VIFS="wi0"
	#ENABLE_VIFS="ed1"
	;;

	pie)
	ENABLE_VIFS="en1"
	;;

	*)
	echo "Unknown host : ${HOSTNAME}"
	exit 1
	;;
esac

#
# Comment-out to disable log trace
#
MFEA_ENABLE_LOG_TRACE=yes
MLD6IGMP_ENABLE_LOG_TRACE=yes

#
# The subnets to enable/disable CLI access
#
CLI_ENABLE_SUBNETS="127.0.0.1/32 192.150.187.0/25"
CLI_DISABLE_SUBNETS="0.0.0.0/0"		# Disable everything else


###############################################################
# USER CONFIGURATION END
###############################################################


# Add the PIM 'register_vif' to the list of interfaces to enable
MFEA_ENABLE_VIFS="${ENABLE_VIFS} register_vif"
MLD6IGMP_ENABLE_VIFS="${ENABLE_VIFS}"

#
# Disable log trace
#
if [ "${MFEA_ENABLE_LOG_TRACE}" != "yes" ] ; then
	mfea_disable_log_trace
fi
if [ "${MLD6IGMP_ENABLE_LOG_TRACE}" != "yes" ] ; then
	mld6igmp_disable_log_trace
fi

#
# Configure CLI
#
for subnet in ${CLI_ENABLE_SUBNETS}; do
	# XXX: for now, the CLI access is always over IPv4
	cli_add_enable_cli_access_from_subnet4 ${subnet}
done
for subnet in ${CLI_DISABLE_SUBNETS}; do
	# XXX: for now, the CLI access is always over IPv4
	cli_add_disable_cli_access_from_subnet4 ${subnet}
done

#
# Enable and start CLI
#
cli_enable_cli
cli_start_cli

#
# Enable and start MFEA CLI
#
mfea_enable_cli
mfea_start_cli

#
# Enable and start MFEA
#
mfea_enable_mfea
mfea_start_mfea

#
# Enable and start MFEA vifs
#
for vif in ${MFEA_ENABLE_VIFS}; do
	mfea_enable_vif ${vif}
	mfea_start_vif ${vif}
done


#
# Enable and start MLD6IGMP CLI
#
mld6igmp_enable_cli
mld6igmp_start_cli

#
# Enable and start MLD6IGMP
#
mld6igmp_enable_mld6igmp
mld6igmp_start_mld6igmp

#
# Wait to get the list of vifs
#
mld6igmp_is_vif_setup_completed

#
# Enable and start MLD6IGMP vifs
#
for vif in ${MLD6IGMP_ENABLE_VIFS}; do
	mld6igmp_enable_vif ${vif}
	mld6igmp_start_vif ${vif}
done


#
# Done
#
echo "Configuration done."

exit 0
