# Copyright (c) 2009 XORP, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, Version 2, June
# 1991 as published by the Free Software Foundation. Redistribution
# and/or modification of this program under the terms of any other
# version of the GNU General Public License is not permitted.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. For more details,
# see the GNU General Public License, Version 2, a copy of which can be
# found in the XORP LICENSE.gpl file.
#
# XORP Inc, 2953 Bunker Hill Lane, Suite 204, Santa Clara, CA 95054, USA;
# http://xorp.net

# $XORP$

import os
Import('env')

env = env.Clone()

env.AppendUnique(CPPPATH = [
    '#',
    '$BUILDDIR',
    ])

env.AppendUnique(LIBPATH = [
    '../libxorp',
    '../libcomm',
    '../libxipc',
    '../libproto',
    '../libfeaclient',
    '../policy/backend',
    '../policy/common',
    '../xrl/interfaces',
    '../xrl/targets',
    '../mrt',
    '.'
    ])

env.AppendUnique(LIBS = [
    'mld6igmp',
    'feaclient',
    'mld6igmpclientxif',
    'fearawpkt4xif',
    'fearawpkt6xif',
    'feaifmgrmirrorxif',
    'feaifmgrreplicatorxif',
    'climanagerxif',
    'findereventnotifierxif',
    'feaifmgrmirrorbase',
    'mld6igmpbase',
    'mrt',
    'xipc',
    'xorp',
    'proto',
    'comm'
])

libmld6igmpsrcs = [
	     'mld6igmp_config.cc',
	     'mld6igmp_group_record.cc',
	     'mld6igmp_node.cc',
	     'mld6igmp_node_cli.cc',
	     'mld6igmp_proto.cc',
	     'mld6igmp_source_record.cc',
	     'mld6igmp_vif.cc',
	     'xrl_mld6igmp_node.cc'
             ]

libmld6igmp = env.SharedLibrary(target = 'libmld6igmp', source = libmld6igmpsrcs, LIBS = '')


igmpsrcs = [
          'xorp_igmp.cc',
          ]

igmp = env.Program(target = 'xorp_igmp', source = igmpsrcs)

mldsrcs = [
          'xorp_mld.cc',
          ]

mld = env.Program(target = 'xorp_mld', source = mldsrcs)

#mldpath = '$bindir'
mldpath = '$exec_prefix' + '/' + 'mld6igmp'

env.Alias('install',
          env.InstallProgram(mldpath, igmp))

env.Alias('install',
          env.InstallProgram(mldpath, mld))

env.Alias('install',
          env.InstallLibrary('$libdir', libmld6igmp))

Default(igmp, mld)
