# Copyright (c) 2009-2011 XORP, Inc and Others
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, Version 2, June
# 1991 as published by the Free Software Foundation. Redistribution
# and/or modification of this program under the terms of any other
# version of the GNU General Public License is not permitted.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. For more details,
# see the GNU General Public License, Version 2, a copy of which can be
# found in the XORP LICENSE.gpl file.
#
# XORP Inc, 2953 Bunker Hill Lane, Suite 204, Santa Clara, CA 95054, USA;
# http://xorp.net
#
# $Id$

import os
Import("env")

env = env.Clone()

manual_srcs = [
	'user_manual.tex',
	#'bgp.tex',
	#'cli_intro.tex',
	#'config_overview.tex',
	#'diagnostics.tex',
	#'firewall.tex',
	#'forwarding.tex',
	#'glossary.tex',
	#'igmp.tex',
	#'interfaces.tex',
	#'livecd.tex',
	#'multicast_routing.tex',
	#'multicast_topology.tex',
	#'ospf.tex',
	#'pimsm.tex',
	#'policy.tex',
	#'preface.tex',
	#'rip.tex',
	#'snmp.tex',
	#'static_routes.tex',
	#'unicast_routing.tex',
	#'users.tex',
	#'vrrp.tex',
	]

env.PrependUnique(TEXINPUTS = [
	os.path.join(env['sourcedir'], 'user_manual'),
])

manual_pdf = env.PDF(env.DVI(target='user_manual', source=manual_srcs))
manual_ps = env.PostScript(env.DVI(target='user_manual', source=manual_srcs))

Default(manual_pdf, manual_ps)
