#!/bin/sh

DIR=`dirname $0`
: ${DIR:="."}

riptype=$1
shift

if [ ${riptype} != "rip" -a ${riptype} != "ripng" ] ; then
    echo "Expected first argument to be \"rip\" or \"ripng\": got \"${riptype}\""
    exit
fi

# Source RIP specific shell functions
. ${DIR}/xrl_${riptype}_shell_funcs.sh

# Source library shell functions
. ${DIR}/../../utils/xrl_shell_lib.sh

CALLXRL="${DIR}/../../libxipc/call_xrl"

CMDS="delete static"
for i in ${CMDS} ; do
    if [ "${1}" != "${i}" ] ; then
	echo "Unexpected argument: ${1} (!= ${i})."
	exit 1
    fi
    shift
done

if [ $# -ne 1 ] ; then
    echo "Expected <net> but got $*"
    exit 1
fi

RIPCMD="${riptype}_${riptype}_delete_static_route"
${RIPCMD} $1

exit 0

