#!/bin/sh

#
# $XORP: xorp/fea/command_mfea,v 1.1 2003/06/03 21:54:42 pavlin Exp $
#

#
# Send commands to a running MFEA process.
#

# Conditionally set ${srcdir} if it wasn't assigned (e.g., by `gmake check`)
if [ "X${srcdir}" = "X" ] ; then srcdir=`dirname $0` ; fi

. ${srcdir}/../cli/xrl_cli_shell_funcs.sh
. ${srcdir}/../fea/xrl_mfea_shell_funcs.sh

MODULE_NAME="MFEA"
HOSTNAME=`hostname`

echo "Sending command to $MODULE_NAME on $HOSTNAME..."

#
# The first argument should be the command to call.
# The rest of the arguments should be the arguments to the command to call.
#

if [ $# -lt 1 ] ; then
	echo "Usage: $0 <xrl_command> [xrl_command_arguments ... ]"
	exit 1
fi

$*

exit 0
