# Copyright (c) 2009 XORP, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, Version 2, June
# 1991 as published by the Free Software Foundation. Redistribution
# and/or modification of this program under the terms of any other
# version of the GNU General Public License is not permitted.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. For more details,
# see the GNU General Public License, Version 2, a copy of which can be
# found in the XORP LICENSE.gpl file.
#
# XORP Inc, 2953 Bunker Hill Lane, Suite 204, Santa Clara, CA 95054, USA;
# http://xorp.net

# $XORP$

import os
Import('env')

env = env.Clone()

is_shared = env.has_key('SHAREDLIBS')

env.AppendUnique(CPPPATH = [
    '#',
    '$BUILDDIR',
     ])

env.AppendUnique(LIBPATH = [
    '$BUILDDIR/libxorp',
    '$BUILDDIR/libcomm',
    '$BUILDDIR/libxipc',
    '$BUILDDIR/libproto',
    '$BUILDDIR/xrl/interfaces',
    '$BUILDDIR/xrl/targets',
    '.',
    ])

env.AppendUnique(LIBS = [
    'ospfv2xif',
    'ospfv3xif',
    'xipc',
    'xorp',
    'proto',
    'comm',
    ])

cleardbsrcs = [
	'clear_database.cc'
    ]

printlsassrcs = [
	'print_lsas.cc',
    ]

# deal with shared code
if is_shared:
    printlsassrcs += [ '../lsa.cc', '../fletcher_checksum.cc' ]
else:
    obj_fletcher = env.StaticObject(target='tools_fletcher',
                                    source='../fletcher_checksum.cc')
    obj_lsa = env.StaticObject(target='tools_lsa', source='../lsa.cc')
    printlsassrcs += [ obj_fletcher, obj_lsa ]

printneighborssrcs = [
        'print_neighbours.cc'
    ]

cleardb = env.Program(target = 'clear_database', source = cleardbsrcs)

printlsas = env.Program(target = 'print_lsas', source = printlsassrcs)

printneighbors = env.Program(target = 'print_neighbours', source = printneighborssrcs)

#ospftoolpath = '$bindir'
ospftoolpath = '$exec_prefix/ospf/tools'

env.Alias('install',
    env.InstallProgram(ospftoolpath, cleardb))

env.Alias('install',
    env.InstallProgram(ospftoolpath, printlsas))

env.Alias('install',
    env.InstallProgram(ospftoolpath, printneighbors))

Default(cleardb, printlsas, printneighbors)
