#! /bin/sh
#
# Load a mib module 
#     
#  $ loadbgp /home/jsmith/mymibs/bgp4_mib_1657.so 2
#
# Requires:
#
#  (1) that snmpd is running
#
#  (2) that the XORP interface module (xorp_if_mib_module) is loaded
#

set -x

if test "$1" = "" -o "$2" = "" ; then
    echo 'usage example:  '
    echo '    $ loadbgp bgp4_mib_1657 2' 
    exit 1
fi

MIBS_PATH=`(cd ..; pwd)`
MOD_FILENAME="${MIBS_PATH}/$1.so" 

echo "Loading module $1 from ${MOD_FILENAME}..."

snmpset localhost UCD-DLMOD-MIB::dlmodStatus.$2 i create
snmpset localhost UCD-DLMOD-MIB::dlmodName.$2 s "$1" UCD-DLMOD-MIB::dlmodPath.$2 s "${MOD_FILENAME}"
snmpset localhost UCD-DLMOD-MIB::dlmodStatus.$2 i load
echo "The module $1 should appear as loaded in position $2"
snmptable localhost UCD-DLMOD-MIB::dlmodTable
