#! /bin/sh
#
# Load bgp4_mib_1657 module into snmpd in the position specified in the first
# parameter. Example:   
#     
#  $ loadbgp 2
#
# Requires:
#
#  (1) that snmpd is running
#
#  (2) that the XORP interface module (xorp_if_mib_module) is loaded
#

 . ../snmpconfig/snmpenv.sh

snmpset localhost UCD-DLMOD-MIB::dlmodStatus.$1 i create
snmpset localhost UCD-DLMOD-MIB::dlmodName.$1 s "bgp4_mib_1657" UCD-DLMOD-MIB::dlmodPath.$1 s "${XORP}/mibs/bgp4_mib_1657.so"
snmpset localhost UCD-DLMOD-MIB::dlmodStatus.$1 i load
echo "The BGP module should appear as loaded in position $1"
snmptable localhost UCD-DLMOD-MIB::dlmodTable
