#! /bin/sh


snmpd -L -f -Dsnmp_alarm,SnmpEventLoop,ospf_mib_1850,xorp_if_mib_module,bgp4_mib_1657,bgp4_mib_1657_bgpversion,bgp4_mib_1657_bgppeertable -c ../snmpconfig/snmpd.conf -I -ipv6 -r udp:localhost:51515

