#! /bin/sh

export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:..

snmpd -L -f -Dbgp4_mib_1657 -c ../snmpconfig/snmpd.conf -I -ipv6 -r udp:localhost:51515


# useful debug tokens that can be appended to the -D list
#
# snmp_alarm,SnmpEventLoop,ospf_mib_1850,xorp_if_mib_module
