#! /bin/sh

 . ../snmpconfig/snmpenv.sh

snmpd -L -f -Dbgp4_mib_1657,xorp_if_mib_module,dlmod,SnmpEventLoop -c ../snmpconfig/snmpd.conf -I -ipv6 -r udp:localhost:51515


# useful debug tokens that can be appended to the -D list
#
# snmp_alarm,SnmpEventLoop,ospf_mib_1850,xorp_if_mib_module,bgp4_mib_1657,dlmod
