# Copyright (c) 2009 XORP, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, Version 2, June
# 1991 as published by the Free Software Foundation. Redistribution
# and/or modification of this program under the terms of any other
# version of the GNU General Public License is not permitted.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. For more details,
# see the GNU General Public License, Version 2, a copy of which can be
# found in the XORP LICENSE.gpl file.
#
# XORP Inc, 2953 Bunker Hill Lane, Suite 204, Santa Clara, CA 95054, USA;
# http://xorp.net

# $XORP$

import os
Import('env')

e = env.Clone()

cmds = [
    'bgp',
    'fea',
    'host',
    'igmp',
    'mfea',
    'mfea6',
    'misc',
    'mld',
    #'olsr4', #notyet
    'ospfv2',
    'ospfv3',
    'pim',
    'pim6',
    'policy',
    'rib',
    'rip',
    'ripng',
    'vrrp',
    'xorpsh',
]

tps = [
    'bgp',
    'fea',
    'fib2mrib',
    'firewall',
    'igmp',
    'interfaces',
    'mfea4',
    'mfea6',
    'mld',
    #'olsr4', #notyet
    'ospfv2',
    'ospfv3',
    'pimsm4',
    'pimsm6',
    'plumbing',
    'policy',
    'protocols',
    'rib',
    'rip',
    'ripng',
    'rtrmgr',
    'static_routes',
    'vrrp',
]

e.Alias('install', [
        e.InstallData(env['xorp_templatedir'],
                      [c.__add__('.cmds') for c in cmds]),
        e.InstallData(env['xorp_templatedir'],
                      [t.__add__('.tp') for t in tps])
])
