# Copyright (c) 2009 XORP, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, Version 2, June
# 1991 as published by the Free Software Foundation. Redistribution
# and/or modification of this program under the terms of any other
# version of the GNU General Public License is not permitted.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. For more details,
# see the GNU General Public License, Version 2, a copy of which can be
# found in the XORP LICENSE.gpl file.
#
# XORP Inc, 2953 Bunker Hill Lane, Suite 204, Santa Clara, CA 95054, USA;
# http://xorp.net

# $ID$

Import('env')

subdirs = [
	'bgp',
	'design_arch',
	'fea',
	#'kdoc',		# notyet
	'libxipc',
	'libxorp',
	'man',
	'mfea',
	'mld6igmp',
	'multicast',
	'olsr',
	#'papers',		# old content
	'pim',
	'pim_testsuite',
	'policy',
	'rib',
	'rip',
	'rtrmgr',
	#'slides',		# old content
	#'snmp',		# old content
	'test_harness',
	'user_manual',
	'windows_port',
	'xorpdev_101',
	]

SConscript(dirs = subdirs, exports='env')
