# Copyright (c) 2009 XORP, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, Version 2, June
# 1991 as published by the Free Software Foundation. Redistribution
# and/or modification of this program under the terms of any other
# version of the GNU General Public License is not permitted.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. For more details,
# see the GNU General Public License, Version 2, a copy of which can be
# found in the XORP LICENSE.gpl file.
#
# XORP Inc, 2953 Bunker Hill Lane, Suite 204, Santa Clara, CA 95054, USA;
# http://xorp.net

# $ID$

Import('env')

subdirs = [
    #'etc/templates',  # FIXME for install
    'cli',
    'xrl/targets',
    'xrl/interfaces',
    'libxipc',
    'libproto',
    'libcomm',
    'libxorp',
    'libfeaclient',
    'fea',
    'fib2mrib',
    'mld6igmp',
    'mrt',
    'ospf',
    'pim',
    'policy',
    'rib',
    'rip',
    'rtrmgr',
    'static_routes',
    'vrrp',
    'bgp',
    #'contrib/olsr',
    #'contrib/mld6igmp_lite',
    ]

SConscript(dirs = subdirs, exports='env')
