# Copyright (c) 2009-2011 XORP, Inc and Others
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, Version 2, June
# 1991 as published by the Free Software Foundation. Redistribution
# and/or modification of this program under the terms of any other
# version of the GNU General Public License is not permitted.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. For more details,
# see the GNU General Public License, Version 2, a copy of which can be
# found in the XORP LICENSE.gpl file.
#
# XORP Inc, 2953 Bunker Hill Lane, Suite 204, Santa Clara, CA 95054, USA;
# http://xorp.net

# $XORP$

import os
Import('env')

env = env.Clone()

env.AppendUnique(CPPPATH = [
    '#',
    '$BUILDDIR',
     ])

env.AppendUnique(LIBPATH = [
    '$BUILDDIR/libxorp',
    '$BUILDDIR/libcomm',
    '$BUILDDIR/libxipc',
    '$BUILDDIR/libproto',
    '$BUILDDIR/xrl/interfaces',
    '$BUILDDIR/xrl/targets',
    '.',
    ])

env.AppendUnique(LIBS = [
    'xif_finder_event_notifier',
    'xif_rib',
    'xst_show_distances',
    'xst_show_routes',
    'xorp_ipc',
    'xorp_core',
    'xorp_proto',
    'xorp_comm',
    ])

is_shared = env.has_key('SHAREDLIBS')

if not is_shared:
    env.AppendUnique(LIBS = [
        "crypto",
        ])

    if not (env.has_key('mingw') and env['mingw']):
        env.AppendUnique(LIBS = [
            "rt",
            ])

if (env.has_key('mingw') and env['mingw']):
    env.AppendUnique(LIBS = [
        'ws2_32',
        'iphlpapi',
        'winmm',
#        'mprapi',
#        'regex',
        ])

    env.Append(LIBS = ['xorp_core'])


env.Replace(RPATH = [
    env.Literal(env['xorp_tool_rpath'])
])

shdistsrcs = [
	'show_distances.cc'
    ]

shrtessrcs = [
	'show_routes.cc'
    ]

shdist = env.Program(target = 'rib_show_distances', source = shdistsrcs)
shrtes = env.Program(target = 'rib_show_routes', source = shrtessrcs)

env.Alias('install', env.InstallProgram(env['xorp_tooldir'], shdist))
env.Alias('install', env.InstallProgram(env['xorp_tooldir'], shrtes))

Default(shdist, shrtes)
