# Copyright (c) 2009 XORP, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, Version 2, June
# 1991 as published by the Free Software Foundation. Redistribution
# and/or modification of this program under the terms of any other
# version of the GNU General Public License is not permitted.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. For more details,
# see the GNU General Public License, Version 2, a copy of which can be
# found in the XORP LICENSE.gpl file.
#
# XORP Inc, 2953 Bunker Hill Lane, Suite 204, Santa Clara, CA 95054, USA;
# http://xorp.net

# $XORP$

import os
Import('env')

env = env.Clone()

env.AppendUnique(CPPPATH = [
    '#',
    '$BUILDDIR',
    ])

env.AppendUnique(LIBPATH = [
    '../libxorp',
    '../libcomm',
    '../libxipc',
    '../libproto',
    '../libfeaclient',
    '../policy/backend',
    '../policy/common',
    '../xrl/interfaces',
    '../xrl/targets',
    '.'
    ])

env.AppendUnique(LIBS = [
    'staticroutes',
    'feaclient',
    'feaifmgrmirrorxif',
    'feaifmgrreplicatorxif',
    'fearawlinkxif',
    'findereventnotifierxif',
    'feaifmgrmirrorbase',
    'staticroutesbase',
    'ribxif',
    'findereventnotifierxif',
    'policybackend',
    'policycommon',
    'xipc',
    'xorp',
    'proto',
    'comm',
    ])


libsrsources = [
    'static_routes_node.cc',
    'static_routes_varrw.cc',
    'xrl_static_routes_node.cc'
    ]

srsources = [
    'xorp_static_routes.cc'
    ]

libsr = env.SharedLibrary(LIBS = '', target = 'libstaticroutes', source = libsrsources)

xorp_static_routes = env.Program(target = 'xorp_static_routes', source = srsources)

#srpath = '$bindir'
srpath = '$exec_prefix/static_routes'

env.Alias('install',
          env.InstallProgram(srpath, xorp_static_routes))

env.Alias('install',
          env.InstallLibrary('$libdir', libsr))

Default(xorp_static_routes)
