# Copyright (c) 2009 XORP, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, Version 2, June
# 1991 as published by the Free Software Foundation. Redistribution
# and/or modification of this program under the terms of any other
# version of the GNU General Public License is not permitted.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. For more details,
# see the GNU General Public License, Version 2, a copy of which can be
# found in the XORP LICENSE.gpl file.
#
# XORP Inc, 2953 Bunker Hill Lane, Suite 204, Santa Clara, CA 95054, USA;
# http://xorp.net

# $XORP$

import os
Import('env')

env = env.Clone()

is_shared = env.has_key('SHAREDLIBS')

env.AppendUnique(CPPPATH = [
    '#',
    '$BUILDDIR',
    ])

env.PrependUnique(LIBPATH = [
    '$BUILDDIR/libxorp',
    '$BUILDDIR/libcomm',
    '$BUILDDIR/libxipc',
    '$BUILDDIR/libproto',
    '$BUILDDIR/libfeaclient',
    '$BUILDDIR/policy/backend',
    '$BUILDDIR/policy/common',
    '$BUILDDIR/xrl/interfaces',
    '$BUILDDIR/xrl/targets',
    '.'
    ])

env.AppendUnique(LIBS = [
    'staticroutes',
    'xorp_fea_client',
    'feaifmgrmirrorxif',
    'feaifmgrreplicatorxif',
    'findereventnotifierxif',
    'feaifmgrmirrorbase',
    'staticroutesbase',
    'ribxif',
    'findereventnotifierxif',
    'policybackend',
    'policycommon',
    'xipc',
    'xorp',
    'xorp_proto',
    'xorp_comm',
    ])


libsrsources = [
    'static_routes_node.cc',
    'static_routes_varrw.cc',
    'xrl_static_routes_node.cc'
    ]

srsources = [
    'xorp_static_routes.cc'
    ]

if is_shared:
    libsr = env.SharedLibrary(LIBS = '', target = 'libstaticroutes', source = libsrsources)
else:
    libsr = env.StaticLibrary(LIBS = '', target = 'libstaticroutes', source = libsrsources)

xorp_static_routes = env.Program(target = 'xorp_static_routes', source = srsources)

#srpath = '$bindir'
srpath = '$exec_prefix/static_routes'

env.Alias('install',
          env.InstallProgram(srpath, xorp_static_routes))

if is_shared:
    env.Alias('install',
              env.InstallLibrary('$libdir', libsr))

Default(xorp_static_routes)
