# Copyright (c) 2009 XORP, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, Version 2, June
# 1991 as published by the Free Software Foundation. Redistribution
# and/or modification of this program under the terms of any other
# version of the GNU General Public License is not permitted.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. For more details,
# see the GNU General Public License, Version 2, a copy of which can be
# found in the XORP LICENSE.gpl file.
#
# XORP Inc, 2953 Bunker Hill Lane, Suite 204, Santa Clara, CA 95054, USA;
# http://xorp.net

# $XORP$

import os
Import('env')

env = env.Clone()

env.AppendUnique(CPPPATH = [
    '#',
    '$BUILDDIR',
     ])

env.AppendUnique(LIBPATH = [
    '$BUILDDIR/libxorp',
    '$BUILDDIR/libcomm',
    '$BUILDDIR/libxipc',
    '$BUILDDIR/libproto',
    '$BUILDDIR/xrl/interfaces',
    '$BUILDDIR/xrl/targets',
    '.',
    ])

env.AppendUnique(LIBS = [
    'libcliprocessorxif',
    'xipc',
    'xorp',
    'proto',
    'xorp_comm',
    ])

cligensrcs = [
	'cli_generic.cc'
    ]

sendclisrcs = [
	'send_cli_processor_xrl.cc'
    ]

cligen = env.Program(target = 'cli_generic', source = cligensrcs)

sendcli = env.Program(target = 'send_cli_processor_xrl', source = sendclisrcs)

#clitoolpath = '$bindir'
clitoolpath = '$exec_prefix/cli/tools'

env.Alias('install',
    env.InstallProgram(clitoolpath, cligen))

env.Alias('install',
    env.InstallProgram(clitoolpath, sendcli))

Default(cligen, sendcli)
