ARG FEDORA_VERSION=40
FROM fedora:${FEDORA_VERSION}

RUN dnf update -y && dnf install -y \
    bison cmake diffutils \
    flex gcc gcc-c++ git \
    ncurses-devel libnfnetlink-devel \
    libpcap-devel openssl-devel m4 make \
    python3 \
    && dnf clean all

COPY xorp /xorp
RUN mkdir /xorp/build
WORKDIR /xorp/build
RUN cmake -DBUILD_INFO=OFF -DTESTS_PROGRAMS=ON \
    -DDISABLE_WDEPRECATED=ON -DCMAKE_BUILD_SHARED_LIBS=ON .. \
    && make -j$(nproc)

