/*
 * Copyright (c) 2002 International Computer Science Institute
 * See LICENSE file for licensing, conditions, and warranties on use.
 *
 * DO NOT EDIT THIS FILE - IT IS PROGRAMMATICALLY GENERATED
 *
 * Generated by '../scripts/clnt-gen'.
 *
 * $XORP: xorp/xrl/interfaces/common_xif.hh,v 1.2 2002/12/14 23:43:11 hodson Exp $
 */


#ifndef __XRL_INTERFACES_COMMON_XIF_HH__
#define __XRL_INTERFACES_COMMON_XIF_HH__

#undef XORP_LIBRARY_NAME
#define XORP_LIBRARY_NAME "XifCommon"
#include "libxorp/xlog.h"
#include "libxipc/xrl_router.hh"

class XrlCommonV0p1Client {
public:
    XrlCommonV0p1Client(XrlSender* r) : _router(r) {}
    virtual ~XrlCommonV0p1Client() {}

    typedef XorpCallback2<void, const XrlError&, const string*>::RefPtr CB0;
    /**
     *  Send Xrl intended to:
     *  
     *  Get name of Xrl Target
     *  
     *  @param tgt_name Xrl Target name
     */
    bool send_get_target_name(
	const char*	target_name, 
	const CB0&	cb
    );

    typedef XorpCallback2<void, const XrlError&, const string*>::RefPtr CB1;
    /**
     *  Send Xrl intended to:
     *  
     *  Get version string from Xrl Target
     *  
     *  @param tgt_name Xrl Target name
     */
    bool send_get_version(
	const char*	target_name, 
	const CB1&	cb
    );

protected:
    XrlSender* _router;

private:
    void unmarshall0(
	const XrlError&	e, 
	XrlArgs*	a, 
	CB0		cb
    );

    void unmarshall1(
	const XrlError&	e, 
	XrlArgs*	a, 
	CB1		cb
    );

};

#endif /* __XRL_INTERFACES_COMMON_XIF_HH__ */
