/*
 * Copyright (c) 2001-2003 International Computer Science Institute
 * See LICENSE file for licensing, conditions, and warranties on use.
 *
 * DO NOT EDIT THIS FILE - IT IS PROGRAMMATICALLY GENERATED
 *
 * Generated by 'clnt-gen'.
 */

#ident "$XORP: xorp/xrl/interfaces/fea_rawpkt_client_xif.cc,v 1.5 2003/03/10 23:01:27 hodson Exp $"

#include "fea_rawpkt_client_xif.hh"

bool
XrlRawPacketClientV0p1Client::send_recv_raw4(
	const char*	the_tgt, 
	const string&	if_name, 
	const string&	vif_name, 
	const vector<uint8_t>&	packet, 
	const CB0&	cb
)
{
    Xrl x(the_tgt, "raw_packet_client/0.1/recv_raw4");
    x.args().add("if_name", if_name);
    x.args().add("vif_name", vif_name);
    x.args().add("packet", packet);
    return _sender->send(x, callback(this, &XrlRawPacketClientV0p1Client::unmarshall0, cb));
}


/* Unmarshall recv_raw4 */
void
XrlRawPacketClientV0p1Client::unmarshall0(
	const XrlError&	e, 
	XrlArgs*	a, 
	CB0		cb
)
{
    if (e != XrlError::OKAY()) {
	cb->dispatch(e);
	return;
    } else if (a && a->size() != 0) {
	XLOG_ERROR("Wrong number of arguments (%u != 0)", (uint32_t)a->size());
	cb->dispatch(XrlError::BAD_ARGS());
	return;
    }
    cb->dispatch(e);
}
