#
# Set FIG_SOURCES to list of .fig sources
# A postscript and a pdf file will be generated for each.
#
TARGETS=$(FIG_SOURCES:%.fig=%.eps) 
DISABLED_TARGETS=$(FIG_SOURCES:%.fig=%.pdf)

all: $(TARGETS)

%.pdf: %.ps
	epstopdf $<

%.ps: %.fig
	fig2dev -Lps $< $@

%.eps: %.fig
	fig2dev -Leps $< $@

clean:
	rm -f $(TARGETS) *~
