# Copyright (c) 2009-2011 XORP, Inc and Others
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, Version 2, June
# 1991 as published by the Free Software Foundation. Redistribution
# and/or modification of this program under the terms of any other
# version of the GNU General Public License is not permitted.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. For more details,
# see the GNU General Public License, Version 2, a copy of which can be
# found in the XORP LICENSE.gpl file.
#
# XORP Inc, 2953 Bunker Hill Lane, Suite 204, Santa Clara, CA 95054, USA;
# http://xorp.net
#
# $Id$

import os
Import("env")

env = env.Clone()
lx_pdf = env.PDF(env.DVI('libxipc_overview.tex'))
lx_ps = env.PostScript(env.DVI('libxipc_overview.tex'))

# XXX Embedded paths need updated to XIF files.
# This assumes that XORP source from this branch is checked out
# in the directory above (normal SVN repo layout).
# A few files are now generated on demand; these are checked in here.
env = env.Clone()
env.AppendUnique(TEXINPUTS = [
	env['sourcedir'] + '/../xorp/' + ':',
	env['sourcedir'] + '/libxipc/' + ':',
	])

# This breaks for one reason or another. --Ben
#xi_pdf = env.PDF(env.DVI('xrl_interfaces.tex'))
#xi_ps = env.PostScript(env.DVI('xrl_interfaces.tex'))
#Default(lx_pdf, xi_pdf, lx_ps, xi_ps)

Default(lx_pdf, lx_ps)
