#!/usr/bin/perl -w
#
# $XORP: CVSROOT/verifymsgcheck,v 1.2 2004/07/30 23:44:51 pavlin Exp $
# $FreeBSD: CVSROOT-src/verifymsgcheck,v 1.1 2004/03/30 00:18:16 kuriyama Exp $
#

use strict;
use lib $ENV{CVSROOT};
use CVSROOT::cfg;
my $CVSROOT = $ENV{CVSROOT} || die "Can't determine CVSROOT (verifymsgcheck)!\n";

# Check "Approved by:" line.
system("$CVSROOT/CVSROOT/approvecheck", @ARGV);
if ($? >> 8) {
	exit 1;
}

# peter's edit post-processor..
system("$CVSROOT/CVSROOT/logcheck", @ARGV);
if ($? >> 8) {
	exit 1;
}
