#! /bin/sh
#
# $XORP: CVSROOT/wrap,v 1.2 2004/07/30 23:44:51 pavlin Exp $
# $FreeBSD: CVSROOT-src/wrap,v 1.3 1999/08/27 22:46:57 peter Exp $
#
#	wrap - Combine a directory into a single tar package.

# This script is always called with the current directory set to
# where the file to be combined exists. but i may get called with a
# path to where cvs first started executing. (this probably should be
# fixed in cvs) so strip out all of the directory information. The
# first sed expression will only work if the path has a leading /
# if it doesn't the one in the if statement will work.
DIRNAME=`echo $1 | sed -e "s|/.*/||g"`
if [ ! -d $DIRNAME ] ; then
      DIRNAME=`echo $1 | sed -e "s|.*/||g"`
fi
#
# Now tar up the directory but we now will only get a relative path
# even if the user did a cvs commit . at the top.
#
tar --preserve -cf - $DIRNAME | gzip --no-name --best -c > $2
