# Copyright (c) 2009 XORP, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, Version 2, June
# 1991 as published by the Free Software Foundation. Redistribution
# and/or modification of this program under the terms of any other
# version of the GNU General Public License is not permitted.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. For more details,
# see the GNU General Public License, Version 2, a copy of which can be
# found in the XORP LICENSE.gpl file.
#
# XORP Inc, 2953 Bunker Hill Lane, Suite 204, Santa Clara, CA 95054, USA;
# http://xorp.net
#
# $Id$

import os
Import("env")

env = env.Clone()

pd_pdf = env.PDF(env.DVI('design.tex'))
pd_ps = env.PostScript(env.DVI('design.tex'))
pi_pdf = env.PDF(env.DVI('implementation.tex'))
pi_ps = env.PostScript(env.DVI('implementation.tex'))
pr_pdf = env.PDF(env.DVI('requirements.tex'))
pr_ps = env.PostScript(env.DVI('requirements.tex'))

Default(pd_pdf, pd_ps, pi_pdf, pi_ps, pr_pdf, pr_ps)
