/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.iterate.conf,v 5.5 2002/12/16 22:50:18 hardaker Exp $
 */
#ifndef BGP4_MIB_1657_BGP4PATHATTRTABLE_H
#define BGP4_MIB_1657_BGP4PATHATTRTABLE_H

/* function declarations */
void init_bgp4_mib_1657_bgp4pathattrtable(void);
void initialize_table_bgp4PathAttrTable(void);
Netsnmp_Node_Handler bgp4PathAttrTable_handler;

Netsnmp_First_Data_Point  bgp4PathAttrTable_get_first_data_point;
Netsnmp_Next_Data_Point   bgp4PathAttrTable_get_next_data_point;

/* column number definitions for table bgp4PathAttrTable */
       #define COLUMN_BGP4PATHATTRPEER		1
       #define COLUMN_BGP4PATHATTRIPADDRPREFIXLEN		2
       #define COLUMN_BGP4PATHATTRIPADDRPREFIX		3
       #define COLUMN_BGP4PATHATTRORIGIN		4
       #define COLUMN_BGP4PATHATTRASPATHSEGMENT		5
       #define COLUMN_BGP4PATHATTRNEXTHOP		6
       #define COLUMN_BGP4PATHATTRMULTIEXITDISC		7
       #define COLUMN_BGP4PATHATTRLOCALPREF		8
       #define COLUMN_BGP4PATHATTRATOMICAGGREGATE		9
       #define COLUMN_BGP4PATHATTRAGGREGATORAS		10
       #define COLUMN_BGP4PATHATTRAGGREGATORADDR		11
       #define COLUMN_BGP4PATHATTRCALCLOCALPREF		12
       #define COLUMN_BGP4PATHATTRBEST		13
       #define COLUMN_BGP4PATHATTRUNKNOWN		14
#endif /* BGP4_MIB_1657_BGP4PATHATTRTABLE_H */
