# Copyright (c) 2009 XORP, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, Version 2, June
# 1991 as published by the Free Software Foundation. Redistribution
# and/or modification of this program under the terms of any other
# version of the GNU General Public License is not permitted.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. For more details,
# see the GNU General Public License, Version 2, a copy of which can be
# found in the XORP LICENSE.gpl file.
#
# XORP Inc, 2953 Bunker Hill Lane, Suite 204, Santa Clara, CA 95054, USA;
# http://xorp.net
#
# $XORP$

import os
Import("env")

env = env.Clone()

env.AppendUnique(CPPPATH = [
	'#',
	'$BUILDDIR',
	'$BUILDDIR/rip',
	'$BUILDDIR/rip/tests',
	])

env.AppendUnique(LIBPATH = [
	'$BUILDDIR/rip',
	'$BUILDDIR/libfeaclient',
	'$BUILDDIR/policy/backend',
	'$BUILDDIR/policy/common',
	'$BUILDDIR/xrl/interfaces',
	'$BUILDDIR/xrl/targets',
	'$BUILDDIR/libxipc',
	'$BUILDDIR/libproto',
	'$BUILDDIR/libxorp',
	'$BUILDDIR/libcomm',
	])

env.AppendUnique(LIBS = [
	'ripbase',
	'rip',
	'ripng',
	'ripxif',
	'findereventnotifierxif',
	'feaclient',
	'feaifmgrmirrorxif',
	'feaifmgrreplicatorxif',
	'feaifmgrmirrorbase',
	'socket4xif',
	'policybackend',
	'policycommon',
	'xipc',
	'xorp',
	'xorp_comm',
	])

simple_cpp_tests = [
	'auth',
	'outputs',
	'packets',
	'request',
	'route_walk',
	'timers',
	'update_queue',
]

cpp_test_targets = []

for ct in simple_cpp_tests:
    cpp_test_targets.append(env.AutoTest(target = 'test_%s' % ct,
                                         source = 'test_%s.cc' % ct))
