	# Copyright (c) 2009 XORP, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, Version 2, June
# 1991 as published by the Free Software Foundation. Redistribution
# and/or modification of this program under the terms of any other
# version of the GNU General Public License is not permitted.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. For more details,
# see the GNU General Public License, Version 2, a copy of which can be
# found in the XORP LICENSE.gpl file.
#
# XORP Inc, 2953 Bunker Hill Lane, Suite 204, Santa Clara, CA 95054, USA;
# http://xorp.net

# $XORP$

import os
Import('env')

subdirs = [
	'libtecla',
	'tests',
	'tools',
	]

SConscript(dirs = subdirs, exports = 'env')

env = env.Clone()
is_shared = env.has_key('SHAREDLIBS')

env.AppendUnique(CPPPATH = [
    '#',
    '$BUILDDIR',
     ])

env.PrependUnique(LIBPATH = [
    '$BUILDDIR/xrl/interfaces',
    '$BUILDDIR/xrl/targets',
    '$BUILDDIR/libxipc',
    '$BUILDDIR/libproto',
    '$BUILDDIR/libcomm',
    '$BUILDDIR/libxorp',
    '$BUILDDIR/cli/libtecla',
    ])

env.AppendUnique(LIBS = [
    'cliprocessorxif',
    'clibase',
    'tecla_xorp',
    'xorp_proto',
    'xipc',
    'xorp_comm',
    'xorp',
    ])

libclisrcs = [
    'cli_client.cc',
    'cli_command.cc',
    'cli_command_pipe.cc',
    'cli_node.cc',
    'cli_node_internal_commands.cc',
    'cli_node_net.cc',
    'xrl_cli_node.cc'
    ]


if is_shared:
    libcli = env.SharedLibrary(target = 'libcli', source = libclisrcs)
    env.Alias('install',
              env.InstallLibrary('$libdir', libcli))
else:
    libcli = env.StaticLibrary(target = 'libcli', source = libclisrcs)

Default(libcli)
