# Copyright (c) 2009 XORP, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, Version 2, June
# 1991 as published by the Free Software Foundation. Redistribution
# and/or modification of this program under the terms of any other
# version of the GNU General Public License is not permitted.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. For more details,
# see the GNU General Public License, Version 2, a copy of which can be
# found in the XORP LICENSE.gpl file.
#
# XORP Inc, 2953 Bunker Hill Lane, Suite 204, Santa Clara, CA 95054, USA;
# http://xorp.net

# $XORP$

import os
Import("env")

env = env.Clone()

env.AppendUnique(CPPPATH = [
	'#',
	'$BUILDDIR',
	'$BUILDDIR/libproto',
	])

env.AppendUnique(LIBPATH = [
	'$BUILDDIR/libproto',
	'$BUILDDIR/xrl/interfaces',
	'$BUILDDIR/xrl/targets',
	'$BUILDDIR/libxipc',
	'$BUILDDIR/libxorp',
	'$BUILDDIR/libcomm',
	])

env.AppendUnique(LIBS = [
	'xorp_proto',
	'xorp',
	'comm',
	])

tests = [
	'checksum',
	'config_node_id',
	'packet',
	#'spt', # XXX notyet
	]

# XXX UNIX environment needs 'srcdir' set to point to source so
# SPT test can find spt_graph1 file.
# XXX No direct dependency on libproto in graph -- fix.

test_targets = []
for t in tests:
    test_targets.append(env.AutoTest(target = 'test_%s' % t,
                                     source = 'test_%s.cc' % t))
