# Copyright (c) 2009-2011 XORP, Inc and Others
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, Version 2, June
# 1991 as published by the Free Software Foundation. Redistribution
# and/or modification of this program under the terms of any other
# version of the GNU General Public License is not permitted.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. For more details,
# see the GNU General Public License, Version 2, a copy of which can be
# found in the XORP LICENSE.gpl file.
#
# XORP Inc, 2953 Bunker Hill Lane, Suite 204, Santa Clara, CA 95054, USA;
# http://xorp.net

# $ID$

Import('env')

subdirs = [
    'cli',
    'libcomm',
    'libxorp',
    'libxipc',
    'libproto',
    'libfeaclient',
    'xrl/targets',
    'xrl/interfaces',
    #'xrl/tests',		# XXX not in use.
    'etc/templates',
    'fea',
    'fib2mrib',
    'mld6igmp',
    'mrt',
    'pim',
    'policy',
    'rib',
    'rtrmgr',
    'static_routes',
    'utils',
    ]

if env['enable_olsr']:
    subdirs.append('contrib/olsr')

if env['enable_wrapper']:
    subdirs.append('contrib/wrapper')

if env['enable_bgp']:
    subdirs.append('bgp')

if env['enable_ospf']:
    subdirs.append('ospf')
    
if env['enable_rip']:
    subdirs.append('rip')

if env['enable_vrrp']:
    subdirs.append('vrrp')

SConscript(dirs = subdirs, exports='env')
