# Copyright (c) 2009 XORP, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, Version 2, June
# 1991 as published by the Free Software Foundation. Redistribution
# and/or modification of this program under the terms of any other
# version of the GNU General Public License is not permitted.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. For more details,
# see the GNU General Public License, Version 2, a copy of which can be
# found in the XORP LICENSE.gpl file.
#
# XORP Inc, 2953 Bunker Hill Lane, Suite 204, Santa Clara, CA 95054, USA;
# http://xorp.net

# $ID$

Import('env')

subdirs = [
    'libcomm',
    'libxorp',
    'libxipc',
    'libproto',
    'libfeaclient',
    'xrl/targets',
    'xrl/interfaces',
    #'xrl/tests',		# XXX not in use.
    'etc/templates',
    'cli',
    'fea',
    'fib2mrib',
    'mrt',
    'ospf',
    'pim',
    'policy',
    'rib',
    'rip',
    'rtrmgr',
    'static_routes',
    'utils',
    'vrrp',
    'bgp',
    ]

if env['enable_olsr']:
    subdirs.append('contrib/olsr')

# IPv6 related stuff should only be enabled when needed.
if not (env.has_key('disable_ipv6') and env['disable_ipv6']):
    subdirs.append('mld6igmp')


SConscript(dirs = subdirs, exports='env')
