# Copyright (c) 2009 XORP, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, Version 2, June
# 1991 as published by the Free Software Foundation. Redistribution
# and/or modification of this program under the terms of any other
# version of the GNU General Public License is not permitted.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. For more details,
# see the GNU General Public License, Version 2, a copy of which can be
# found in the XORP LICENSE.gpl file.
#
# XORP Inc, 2953 Bunker Hill Lane, Suite 204, Santa Clara, CA 95054, USA;
# http://xorp.net

# $XORP$

import os
Import('env')

env = env.Clone()

is_shared = env.has_key('SHAREDLIBS')

env.AppendUnique(CPPPATH = [
    '#',
    '$BUILDDIR',
    ])

env.AppendUnique(LIBPATH = [
    '$BUILDDIR/libxorp',
    '$BUILDDIR/libcomm',
    '$BUILDDIR/libxipc',
    '$BUILDDIR/libproto',
    '$BUILDDIR/libfeaclient',
    '$BUILDDIR/policy/backend',
    '$BUILDDIR/policy/common',
    '$BUILDDIR/xrl/interfaces',
    '$BUILDDIR/xrl/targets',
    '$BUILDDIR/mrt',
    '.'
    ])

env.AppendUnique(LIBS = [
    'mld6igmp',
    'xorp_fea_client',
    'mld6igmpclientxif',
    'fearawpkt4xif',
    'fearawpkt6xif',
    'feaifmgrmirrorxif',
    'feaifmgrreplicatorxif',
    'climanagerxif',
    'findereventnotifierxif',
    'feaifmgrmirrorbase',
    'mld6igmpbase',
    'xorp_mrt',
    'xorp_ipc',
    'xorp',
    'xorp_proto',
    'xorp_comm'
])

libmld6igmplitesrcs = [
	'mld6igmp_config.cc',
	'mld6igmp_group_record.cc',
	'mld6igmp_node.cc',
	'mld6igmp_node_cli.cc',
	'mld6igmp_proto.cc',
	'mld6igmp_source_record.cc',
	'mld6igmp_vif.cc',
	'xrl_mld6igmp_node.cc',
             ]

# XXX needs fixing for new world order

if is_shared:
    libmld6igmplite = env.SharedLibrary(target = 'libmld6igmplite', source = libmld6igmplitesrcs, LIBS = '')
    env.Alias('install',
              env.InstallLibrary('$libdir', libmld6igmplite))
else:
    libmld6igmplite = env.StaticLibrary(target = 'libmld6igmplite', source = libmld6igmplitesrcs, LIBS = '')


igmplitesrcs = [
          'xorp_igmp.cc',
          ]

igmplite = env.Program(target = 'xorp_igmp_lite', source = igmplitesrcs)

mldlitesrcs = [
          'xorp_mld.cc',
          ]

mldlite = env.Program(target = 'xorp_mld_lite', source = mldlitesrcs)

env.Alias('install',
          env.InstallProgram('$bindir', igmplite))

env.Alias('install',
          env.InstallProgram('$bindir', mldlite))


Default(libmld6igmplite, igmplite, mldlite)
