# Copyright (c) 2009 XORP, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, Version 2, June
# 1991 as published by the Free Software Foundation. Redistribution
# and/or modification of this program under the terms of any other
# version of the GNU General Public License is not permitted.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. For more details,
# see the GNU General Public License, Version 2, a copy of which can be
# found in the XORP LICENSE.gpl file.
#
# XORP Inc, 2953 Bunker Hill Lane, Suite 204, Santa Clara, CA 95054, USA;
# http://xorp.net

# $ID$

import os
Import("env")

env = env.Clone()

env.AppendUnique(CPPPATH = [
    '#',
    '$BUILDDIR',
    ])

is_shared = env.has_key('SHAREDLIBS')

sources = [
	# C++ files
	'io_ip_dummy.cc',
	'io_ip_socket.cc',
	'io_link_dummy.cc',
	'io_link_pcap.cc',
	'io_tcpudp_dummy.cc',
	'io_tcpudp_socket.cc',
	]

if is_shared:
    libxio = env.SharedLibrary(target = 'libxorp_fea_io', source = sources)
    env.Alias('install', env.InstallLibrary(env['xorp_libdir'], libxio))
else:
    libxio = env.StaticLibrary(target = 'libxorp_fea_io', source = sources)

Default(libxio)
