# Copyright (c) 2009 XORP, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, Version 2, June
# 1991 as published by the Free Software Foundation. Redistribution
# and/or modification of this program under the terms of any other
# version of the GNU General Public License is not permitted.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. For more details,
# see the GNU General Public License, Version 2, a copy of which can be
# found in the XORP LICENSE.gpl file.
#
# XORP Inc, 2953 Bunker Hill Lane, Suite 204, Santa Clara, CA 95054, USA;
# http://xorp.net

# $XORP$

import os
Import('env')

env = env.Clone()

env.AppendUnique(CPPPATH = [
    '#',
    '$BUILDDIR',
     ])

env.AppendUnique(LIBPATH = [
    '$BUILDDIR/libxorp',
    '$BUILDDIR/libcomm',
    '$BUILDDIR/libxipc',
    '$BUILDDIR/libproto',
    '$BUILDDIR/xrl/interfaces',
    '$BUILDDIR/xrl/targets',
    '.',
    ])

env.AppendUnique(LIBS = [
    'findereventnotifierxif',
    'ribxif',
    'showdistancesbase',
    'showroutesbase',
    'xipc',
    'xorp',
    'proto',
    'comm',
    ])

shdistsrcs = [
	'show_distances.cc'
    ]

shrtessrcs = [
	'show_routes.cc'
    ]

shdist = env.Program(target = 'show_distances', source = shdistsrcs)

shrtes = env.Program(target = 'show_routes', source = shrtessrcs)

#ribtoolpath = '$bindir'
ribtoolpath = '$exec_prefix/rib/tools'

env.Alias('install',
    env.InstallProgram(ribtoolpath, shdist))

env.Alias('install',
    env.InstallProgram(ribtoolpath, shrtes))

Default(shdist, shrtes)
